% SCRIPT FOR GENERATING CONSTANT ACCELERATION DATA,
% WITH MATCHING GYRO DATA.
% IN THE NEXT SCRIPTS WE'LL INTRODUCE NOISE INTO THE MOVEMENT

% device horizontal and facing the user (case 1) 
x = 9.81*ones(500,1);
y = zeros(500,1);
z = zeros(500,1);

